apiVersion: v1
kind: ConfigMap
metadata:
  name: ambassador-nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    worker_rlimit_nofile 4096;
    events {
      worker_connections 512;
    }
    http {
      proxy_set_header HOST $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      upstream backend {
        server brainupgrade.in:80;
      }
      server {
        listen 80;      
        location / {
          # proxy_pass http://backend;
          proxy_pass https://brainupgrade.in:443;
        }
      }
    }  
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-ambassador
spec:
  imagePullSecrets:
    - name:  regcred
  containers:
  - name: main-app
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c","while true;do wget -O /tmp/app.txt localhost ;sleep 30;done"]
  - name: ambassador
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80        
    # volumeMounts:
    #   - name: nginx-config
    #     mountPath: /etc/nginx/nginx.conf
    #     subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: ambassador-nginx-config
